#numpy:
#  - 1.22                  # [win]
#  - 1.22                  # [osx]
#  - 1.22                  # [linux]
#boost:
#  - 1.74                   # [win]
#  - 1.78                   # [osx]
#  - 1.78                   # [linux]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
  - vs2019                     # [win]
compiler_version:
  - 11                         # [osx]
  - 11.2.0                     # [linux]
cxx_compiler_version:
  - 11                         # [osx]
  - 11.2.0                     # [linux]
MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - '10.12'                # [osx]
MACOSX_SDK_VERSION:        # [osx and x86_64]
  - '10.12'                # [osx and x86_64]
pin_run_as_build:
  numpy: x.x
  boost: x.x
  qhull: x.x
  cgap-cpp: x.x
  ann: x.x
  qt-main: x.x
  libpng: x.x
  zlib: x.x
