name: plantgl-doc
channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - conda-forge
dependencies:
  - openalea.plantgl
  - openalea.widgets
  - pip
  - pip:
    - pydata-sphinx-theme
    - myst-parser
    - sphinx-favicon
    - nbsphinx
    - pandoc
    - ipykernel
    - sphinx-copybutton
    - ipython_genutils
